# List of object enabled for picking & placing
# model: gazebo model id
# default_link: gazebo link used for picking for default
# elevation_z: distance in z axis to move the object

objects:
 -
   model: rb1_cart
   default_link: walls
 -
   model: rb1_cart_clone
   default_link: walls

robots:
- 
   model: rb1_base_a
   default_link: rb1_a_base_footprint
   elevation_z: 0.5
- 
   model: rb2_b
   default_link: rb2_b_base_footprint
   elevation_z: 0.5

config:
  # min distance for the simple pick
  min_picking_distance: 0.1
