# List of object enabled for picking & placing
# model: gazebo model id
# default_link: gazebo link used for picking for default
# elevation_z: distance in z axis to move the object

objects:
 -
   model: rb2cart
   default_link: link_0
 -
   model: rb2cart_0
   default_link: link_0

robots:
-
   model: robot
   default_link: robot_base_footprint
   elevation_z: 0.5
-
   model: robot_b
   default_link: robot_b_base_footprint
   elevation_z: 0.5

config:
  # min distance for the simple pick
  min_picking_distance: 0.1
