joint_name: [left_joint,right_joint]
joint_can_id: [1,2]
battery_voltage: 48
battery_amperes: 15
battery_alarm_voltage: 48.5
num_inputs_per_driver: 5
num_outputs_per_driver: 3
# A/h (to simulate battery discharge)
power_consumption: 2
